package cli

import (
	"context"
	"crypto/aes"
	"crypto/cipher"
	"crypto/pbkdf2"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/spf13/cobra"
	"golang.org/x/crypto/argon2"

	"github.com/japananh/aimonitor/internal/daemon"
	"github.com/japananh/aimonitor/internal/provider"
	"github.com/japananh/aimonitor/internal/provider/claude"
	"github.com/japananh/aimonitor/internal/store"
)

// bundleVersion is the format version this build WRITES. Import accepts this
// and older versions it still understands (see bundleVersionMin).
//
//	v1 (≤1.1.1): account identities plaintext; tokens (if any) = encrypted
//	             map[label]base64(stash).
//	v2:          with --include-tokens, the FULL account records — label,
//	             email, org, AND token — live inside the encrypted blob, so the
//	             plaintext file reveals only version + settings. The no-token
//	             bundle still lists plaintext identities (it has no passphrase
//	             to encrypt with; it's the explicitly-shareable variant).
const (
	bundleVersion    = 2
	bundleVersionMin = 1
)

// KDF identifiers stored in the bundle's `kdf` field so import can pick the
// right derivation. New exports use Argon2id; pbkdf2 is kept for decrypting
// bundles written by v1.1.1 (which shipped PBKDF2).
const (
	kdfArgon2id = "argon2id"
	kdfPBKDF2   = "pbkdf2-sha256"
)

// Argon2id parameters — memory-hard, OWASP-recommended baseline
// (m=19 MiB, t=2, p=1). Memory-hardness blunts the GPU/ASIC advantage that
// makes PBKDF2 weaker against offline brute force of a leaked bundle.
const (
	argon2Memory  uint32 = 19456 // KiB (19 MiB)
	argon2Time    uint32 = 2
	argon2Threads uint8  = 1
)

// pbkdf2Iters is the legacy PBKDF2-HMAC-SHA256 work factor — only used now to
// decrypt v1.1.1 bundles whose envelope omits the iteration count.
const pbkdf2Iters = 600_000

// exportBundle is the on-disk shape of `aimonitor config export`. Settings and
// account identities are plaintext (safe to share); credentials, when present
// (--include-tokens), are encrypted under a passphrase in Tokens.
type exportBundle struct {
	Version    int               `json:"version"`
	ExportedAt string            `json:"exported_at,omitempty"`
	Settings   map[string]string `json:"settings"`
	// Accounts holds plaintext identities — present only in the no-token
	// bundle. With --include-tokens it's omitted; identities move inside the
	// encrypted Tokens blob so nothing identifying leaks.
	Accounts []exportAccount  `json:"accounts,omitempty"`
	Tokens   *encryptedTokens `json:"tokens,omitempty"`
}

// exportAccount is an account's identity. In the no-token bundle these are
// plaintext (shareable); in the token bundle they live encrypted (see
// encAccount). organization_uuid comes from Claude (~/.claude.json), not
// generated by aimonitor — so it's part of what gets hidden when encrypted.
type exportAccount struct {
	Label            string `json:"label"`
	Email            string `json:"email,omitempty"`
	OrganizationUUID string `json:"organization_uuid,omitempty"`
	OrganizationName string `json:"organization_name,omitempty"`
}

// encAccount is a full account record sealed inside the v2 encrypted blob:
// identity + the credential. Everything here is hidden until the passphrase
// decrypts it.
type encAccount struct {
	exportAccount
	Token string `json:"token"` // base64(stash bytes)
}

// encryptedTokens is the passphrase-encrypted blob: a KDF (Argon2id, or
// PBKDF2 for v1.1.1 bundles) derives a 32-byte key, AES-256-GCM seals. The
// plaintext is a JSON []encAccount in v2 (identities + tokens) or a
// map[label]base64 in v1. Salt and nonce are random per export.
type encryptedTokens struct {
	KDF string `json:"kdf"` // "argon2id" (new) or "pbkdf2-sha256" (v1.1.1)
	// Argon2id parameters (kdf == "argon2id").
	Memory  uint32 `json:"memory,omitempty"`  // KiB
	Time    uint32 `json:"time,omitempty"`    // iterations
	Threads uint8  `json:"threads,omitempty"` // parallelism
	// PBKDF2 iteration count (kdf == "pbkdf2-sha256").
	Iter       int    `json:"iter,omitempty"`
	Salt       string `json:"salt"`       // base64
	Nonce      string `json:"nonce"`      // base64
	Ciphertext string `json:"ciphertext"` // base64
}

// exportedSettingKeys is the behavioral preferences worth carrying between
// machines. Deliberately NOT update.skipped_version (machine-local) or MCP
// connection state (per-machine tokens).
func exportedSettingKeys() []string {
	return []string{
		daemon.SettingsKeyAutoSwapEnabled,
		daemon.SettingsKeyAutoSwapThreshold,
		daemon.SettingsKeyAutoSwapThreshold7d,
		daemon.SettingsKeyAutoSwapGrace,
		daemon.SettingsKeyNotifyEnabled,
		daemon.SettingsKeyNotifyWarnPct,
		daemon.SettingsKeyNotifyCritPct,
	}
}

func newConfigExportCmd() *cobra.Command {
	var includeTokens bool
	var outPath, passFile string
	cmd := &cobra.Command{
		Use:   "export",
		Short: "Export settings (and optionally encrypted credentials) to a portable bundle",
		Long: `Write a JSON bundle of aimonitor's behavioral settings and account
identities, for replicating your setup on another machine.

By default NO credentials are included — the bundle is safe to share, but the
restored accounts need a credential before they can be used.

With --include-tokens, each account's credential AND identity (label, email,
organization) are sealed together under a passphrase (Argon2id + AES-256-GCM);
the plaintext file then reveals only the version and settings. Set the
passphrase via AIMONITOR_PASSPHRASE or --passphrase-file. THIS FILE CONTAINS
LIVE CLAUDE CREDENTIALS — treat it like a password.`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			return withRuntime(cmd.Context(), func(ctx context.Context, s *store.Store, _ provider.Provider) error {
				return runConfigExport(ctx, cmd, s, includeTokens, outPath, passFile)
			})
		},
	}
	cmd.Flags().BoolVar(&includeTokens, "include-tokens", false, "also bundle credentials, encrypted under a passphrase")
	cmd.Flags().StringVar(&outPath, "out", "", "write to this file instead of stdout")
	cmd.Flags().StringVar(&passFile, "passphrase-file", "", "read the token passphrase from this file (else $AIMONITOR_PASSPHRASE)")
	return cmd
}

func newConfigImportCmd() *cobra.Command {
	var passFile string
	cmd := &cobra.Command{
		Use:   "import <file>",
		Short: "Restore settings (and credentials, if present) from an export bundle",
		Long: `Restore aimonitor settings from a bundle written by "config export".

Settings are always restored. Accounts are restored only when the bundle
carries encrypted credentials (exported with --include-tokens) — supply the
passphrase via AIMONITOR_PASSPHRASE or --passphrase-file. Token-less bundles
just list the account identities for you to re-add manually; no broken,
credential-less rows are created.`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			return withRuntime(cmd.Context(), func(ctx context.Context, s *store.Store, _ provider.Provider) error {
				return runConfigImport(ctx, cmd, s, args[0], passFile)
			})
		},
	}
	cmd.Flags().StringVar(&passFile, "passphrase-file", "", "read the token passphrase from this file (else $AIMONITOR_PASSPHRASE)")
	return cmd
}

func runConfigExport(ctx context.Context, cmd *cobra.Command, s *store.Store, includeTokens bool, outPath, passFile string) error {
	accts, err := s.ListAccounts(ctx)
	if err != nil {
		return fmt.Errorf("list accounts: %w", err)
	}

	bundle := exportBundle{
		Version:    bundleVersion,
		ExportedAt: time.Now().UTC().Format(time.RFC3339),
		Settings:   map[string]string{},
	}
	for _, k := range exportedSettingKeys() {
		v, err := getStoreSetting(ctx, k)
		if err != nil {
			return fmt.Errorf("read setting %s: %w", k, err)
		}
		bundle.Settings[k] = v
	}
	if includeTokens {
		pass, err := resolvePassphrase(passFile)
		if err != nil {
			return err
		}
		// v2: seal the FULL records (identity + token) so the plaintext file
		// reveals nothing identifying — label, email, org, org_uuid all live
		// inside the encrypted blob.
		var recs []encAccount
		for _, a := range accts {
			stash, err := claude.RetrieveStash(ctx, a.KeyringRef)
			if err != nil {
				fmt.Fprintf(cmd.ErrOrStderr(), "warning: skip token for %q: %v\n", a.Label, err)
				continue
			}
			recs = append(recs, encAccount{
				exportAccount: exportAccount{
					Label:            a.Label,
					Email:            a.Email,
					OrganizationUUID: a.OrganizationUUID,
					OrganizationName: a.OrganizationName,
				},
				Token: base64.StdEncoding.EncodeToString(stash.Bytes),
			})
			stash.Zero()
		}
		plain, err := json.Marshal(recs)
		if err != nil {
			return fmt.Errorf("marshal account records: %w", err)
		}
		enc, err := encryptTokens(plain, pass)
		if err != nil {
			return err
		}
		bundle.Tokens = enc
	} else {
		// No passphrase to encrypt with → identities stay plaintext. This is
		// the explicitly-shareable, no-secrets bundle.
		for _, a := range accts {
			bundle.Accounts = append(bundle.Accounts, exportAccount{
				Label:            a.Label,
				Email:            a.Email,
				OrganizationUUID: a.OrganizationUUID,
				OrganizationName: a.OrganizationName,
			})
		}
	}

	out, err := json.MarshalIndent(bundle, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal bundle: %w", err)
	}
	if outPath == "" {
		fmt.Fprintln(cmd.OutOrStdout(), string(out))
		return nil
	}
	// 0600: a token bundle holds credentials; even the plaintext one is the
	// user's config, not world-readable.
	if err := os.WriteFile(outPath, append(out, '\n'), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}
	suffix := ""
	if includeTokens {
		suffix = " (encrypted: identities + credentials)"
	}
	fmt.Fprintf(cmd.OutOrStdout(), "Exported %d settings, %d accounts%s to %s\n",
		len(bundle.Settings), len(accts), suffix, outPath)
	return nil
}

func runConfigImport(ctx context.Context, cmd *cobra.Command, s *store.Store, path, passFile string) error {
	raw, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read %s: %w", path, err)
	}
	var bundle exportBundle
	if err := json.Unmarshal(raw, &bundle); err != nil {
		return fmt.Errorf("parse bundle: %w", err)
	}
	if bundle.Version < bundleVersionMin || bundle.Version > bundleVersion {
		return fmt.Errorf("unsupported bundle version %d (this build understands %d–%d)", bundle.Version, bundleVersionMin, bundleVersion)
	}

	// 1. Settings — always restored. Validate each through the same path as
	// `config set` so a hand-edited bundle can't write a garbage value.
	var setN, skipN int
	for k, v := range bundle.Settings {
		norm, err := validateStoreValue(k, v)
		if err != nil {
			fmt.Fprintf(cmd.ErrOrStderr(), "skip setting %s: %v\n", k, err)
			skipN++
			continue
		}
		if err := s.PutSetting(ctx, k, norm); err != nil {
			return fmt.Errorf("write setting %s: %w", k, err)
		}
		setN++
	}
	fmt.Fprintf(cmd.OutOrStdout(), "Restored %d settings (%d skipped).\n", setN, skipN)

	// 2. Accounts — restored only when the bundle carries credentials, so we
	// never create a credential-less, unusable row.
	if bundle.Tokens == nil {
		if len(bundle.Accounts) > 0 {
			fmt.Fprintf(cmd.OutOrStdout(),
				"\nBundle has no credentials — these %d accounts must be re-added with `aimonitor add`:\n", len(bundle.Accounts))
			for _, a := range bundle.Accounts {
				fmt.Fprintf(cmd.OutOrStdout(), "  - %s (%s)\n", a.Label, a.Email)
			}
		}
		return nil
	}

	pass, err := resolvePassphrase(passFile)
	if err != nil {
		return err
	}
	plain, err := decryptTokens(bundle.Tokens, pass)
	if err != nil {
		return err
	}
	recs, err := decodeAccountRecords(bundle, plain)
	if err != nil {
		return err
	}

	var added, refreshed, failed int
	for _, rec := range recs {
		blob, derr := base64.StdEncoding.DecodeString(rec.Token)
		if derr != nil {
			fmt.Fprintf(cmd.ErrOrStderr(), "skip %q: decode credential: %v\n", rec.Label, derr)
			failed++
			continue
		}
		didAdd, rerr := restoreAccount(ctx, s, rec.exportAccount, blob)
		if rerr != nil {
			fmt.Fprintf(cmd.ErrOrStderr(), "skip %q: %v\n", rec.Label, rerr)
			failed++
			continue
		}
		if didAdd {
			added++
		} else {
			refreshed++
		}
	}
	fmt.Fprintf(cmd.OutOrStdout(), "Accounts: %d added, %d refreshed, %d failed.\n", added, refreshed, failed)
	return nil
}

// decodeAccountRecords reconstructs full records (identity + token) from a
// decrypted payload, handling both bundle formats: v2 sealed the records whole;
// v1 sealed only a label→token map, with identities in the plaintext list.
func decodeAccountRecords(bundle exportBundle, plain []byte) ([]encAccount, error) {
	if bundle.Version >= 2 {
		var recs []encAccount
		if err := json.Unmarshal(plain, &recs); err != nil {
			return nil, fmt.Errorf("parse decrypted records: %w", err)
		}
		return recs, nil
	}
	var tokenMap map[string]string
	if err := json.Unmarshal(plain, &tokenMap); err != nil {
		return nil, fmt.Errorf("parse decrypted tokens: %w", err)
	}
	var recs []encAccount
	for _, a := range bundle.Accounts {
		if tok, ok := tokenMap[a.Label]; ok {
			recs = append(recs, encAccount{exportAccount: a, Token: tok})
		}
	}
	return recs, nil
}

// restoreAccount creates or refreshes an account from an identity + credential
// blob, matching by Claude identity (email + org). Returns true when a new
// account was created (vs an existing one refreshed). Zeroes the credential.
func restoreAccount(ctx context.Context, s *store.Store, id exportAccount, blob []byte) (bool, error) {
	cred := provider.Credential{Bytes: blob}
	defer cred.Zero()

	existing, dErr := s.GetAccountByIdentity(ctx, id.Email, id.OrganizationUUID)
	switch {
	case dErr == nil:
		if err := claude.StashCredential(ctx, existing.KeyringRef, cred); err != nil {
			return false, fmt.Errorf("refresh stash: %w", err)
		}
		_ = s.UpdateAccountIdentity(ctx, existing.ID, id.Email, id.OrganizationUUID, id.OrganizationName)
		return false, nil
	case errors.Is(dErr, store.ErrAccountNotFound):
		ref := uuid.NewString()
		if err := claude.StashCredential(ctx, ref, cred); err != nil {
			return false, fmt.Errorf("stash credential: %w", err)
		}
		if _, err := s.CreateAccount(ctx, store.Account{
			Label:            id.Label,
			Email:            id.Email,
			OrganizationUUID: id.OrganizationUUID,
			OrganizationName: id.OrganizationName,
			KeyringRef:       ref,
		}); err != nil {
			_ = claude.DeleteStash(ctx, ref)
			return false, fmt.Errorf("create account: %w", err)
		}
		return true, nil
	default:
		return false, fmt.Errorf("look up: %w", dErr)
	}
}

// resolvePassphrase sources the token passphrase from --passphrase-file, else
// $AIMONITOR_PASSPHRASE. No interactive prompt (keeps the CLI dependency-free
// and scriptable); a clear error tells the user how to provide one.
func resolvePassphrase(passFile string) (string, error) {
	if passFile != "" {
		b, err := os.ReadFile(passFile)
		if err != nil {
			return "", fmt.Errorf("read passphrase file: %w", err)
		}
		p := strings.TrimRight(string(b), "\r\n")
		if p == "" {
			return "", errors.New("passphrase file is empty")
		}
		return p, nil
	}
	if p := os.Getenv("AIMONITOR_PASSPHRASE"); p != "" {
		return p, nil
	}
	return "", errors.New("a passphrase is required: set $AIMONITOR_PASSPHRASE or pass --passphrase-file <path>")
}

func encryptTokens(plain []byte, passphrase string) (*encryptedTokens, error) {
	salt := make([]byte, 16)
	if _, err := rand.Read(salt); err != nil {
		return nil, fmt.Errorf("salt: %w", err)
	}
	key := argon2.IDKey([]byte(passphrase), salt, argon2Time, argon2Memory, argon2Threads, 32)
	gcm, err := newGCM(key)
	if err != nil {
		return nil, err
	}
	nonce := make([]byte, gcm.NonceSize())
	if _, err := rand.Read(nonce); err != nil {
		return nil, fmt.Errorf("nonce: %w", err)
	}
	ct := gcm.Seal(nil, nonce, plain, nil)
	return &encryptedTokens{
		KDF:        kdfArgon2id,
		Memory:     argon2Memory,
		Time:       argon2Time,
		Threads:    argon2Threads,
		Salt:       base64.StdEncoding.EncodeToString(salt),
		Nonce:      base64.StdEncoding.EncodeToString(nonce),
		Ciphertext: base64.StdEncoding.EncodeToString(ct),
	}, nil
}

func decryptTokens(t *encryptedTokens, passphrase string) ([]byte, error) {
	salt, err := base64.StdEncoding.DecodeString(t.Salt)
	if err != nil {
		return nil, fmt.Errorf("decode salt: %w", err)
	}
	nonce, err := base64.StdEncoding.DecodeString(t.Nonce)
	if err != nil {
		return nil, fmt.Errorf("decode nonce: %w", err)
	}
	ct, err := base64.StdEncoding.DecodeString(t.Ciphertext)
	if err != nil {
		return nil, fmt.Errorf("decode ciphertext: %w", err)
	}
	var key []byte
	switch t.KDF {
	case kdfArgon2id:
		m, ti, th := t.Memory, t.Time, t.Threads
		if m == 0 {
			m = argon2Memory
		}
		if ti == 0 {
			ti = argon2Time
		}
		if th == 0 {
			th = argon2Threads
		}
		key = argon2.IDKey([]byte(passphrase), salt, ti, m, th, 32)
	case kdfPBKDF2, "":
		iter := t.Iter
		if iter <= 0 {
			iter = pbkdf2Iters
		}
		var derr error
		if key, derr = pbkdf2.Key(sha256.New, passphrase, salt, iter, 32); derr != nil {
			return nil, fmt.Errorf("derive key: %w", derr)
		}
	default:
		return nil, fmt.Errorf("unsupported kdf %q", t.KDF)
	}
	gcm, err := newGCM(key)
	if err != nil {
		return nil, err
	}
	pt, err := gcm.Open(nil, nonce, ct, nil)
	if err != nil {
		return nil, errors.New("decrypt failed — wrong passphrase or corrupted bundle")
	}
	return pt, nil
}

func newGCM(key []byte) (cipher.AEAD, error) {
	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, fmt.Errorf("aes cipher: %w", err)
	}
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return nil, fmt.Errorf("gcm: %w", err)
	}
	return gcm, nil
}
