# aimonitor.rb — Homebrew Cask formula.
#
# This is the reference template; the published copy lives in
# japananh/homebrew-tap and is regenerated by goreleaser on every
# release. Goreleaser substitutes :version, :sha256, and the cask URL
# at release time.
#
# To install the latest published release:
#
#     brew tap japananh/tap
#     brew install --cask aimonitor
#
# To install from this file directly (useful when iterating before a
# release tag exists):
#
#     brew install --cask ./packaging/homebrew/aimonitor.rb

cask "aimonitor" do
  version "1.0.0-beta.4"
  sha256 :no_check

  url "https://github.com/japananh/aimonitor/releases/download/v#{version}/aimonitor_#{version}_darwin_universal.tar.gz"
  name "AIMonitor"
  desc "Local-first CLI + macOS menu bar widget for managing multiple Claude OAuth accounts"
  homepage "https://github.com/japananh/aimonitor"

  # Universal binary works on both Intel and Apple Silicon.
  depends_on macos: :sonoma

  binary "aimonitor"
  app "AIMonitor.app"

  # Register the daemon to start at login during install so the menu bar
  # shows live data immediately. must_succeed:false keeps a headless or
  # quarantine-blocked install from failing — the user can run the same
  # command from the caveats. Re-runs on every `brew upgrade`, so the
  # LaunchAgent's recorded binary path self-heals across versions.
  postflight do
    system_command "#{staged_path}/aimonitor",
                   args: ["config", "set", "autostart", "true"],
                   must_succeed: false
  end

  caveats <<~EOS
    The aimonitor daemon is registered to start at login during install,
    so the menu bar shows live data right away. Opt out any time with:

      aimonitor config set autostart false

    The menu bar app is unsigned in this beta — macOS Gatekeeper blocks
    the first GUI launch. Clear it once:

      xattr -dr com.apple.quarantine /Applications/AIMonitor.app

    For COMPLETE removal — including saved logins in your Keychain, the
    database, and config — run this BEFORE `brew uninstall`:

      aimonitor uninstall --purge
  EOS

  # Order matters: brew runs `uninstall` first, then deletes files,
  # then runs `zap` only if --zap was passed. quit + login_item make
  # sure the menu bar app stops AND its SMAppService login-item
  # registration is cleared — otherwise macOS keeps a dangling
  # Login Item pointing at a non-existent /Applications/AIMonitor.app.
  uninstall launchctl:  "dev.aimonitor.daemon",
            quit:       "dev.aimonitor.AIMonitor",
            login_item: "dev.aimonitor.AIMonitor"

  # Sweeps every user-visible FILE. Keychain stashes aren't here — a cask
  # can't enumerate them; `aimonitor uninstall --purge` handles those.
  zap trash: [
    "~/Library/Application Support/aimonitor",
    "~/Library/Logs/aimonitor",
    "~/Library/Caches/aimonitor",
    "~/Library/Preferences/dev.aimonitor.AIMonitor.plist",
    "~/Library/LaunchAgents/dev.aimonitor.daemon.plist",
    "~/.config/aimonitor",
    "~/.aimonitor",
    "~/.aimonitor-lock",
  ]
end
