# aimonitor.rb — Homebrew Cask formula.
#
# This is the reference template; the published copy lives in
# japananh/homebrew-tap and is regenerated by goreleaser on every
# release. Goreleaser substitutes :version, :sha256, and the cask URL
# at release time.
#
# To install the latest published release:
#
#     brew tap japananh/tap
#     brew install --cask aimonitor
#
# To install from this file directly (useful when iterating before a
# release tag exists):
#
#     brew install --cask ./packaging/homebrew/aimonitor.rb

cask "aimonitor" do
  version "1.0.0-beta.3"
  sha256 :no_check

  url "https://github.com/japananh/aimonitor/releases/download/v#{version}/aimonitor_#{version}_darwin_universal.tar.gz"
  name "AIMonitor"
  desc "Local-first CLI + macOS menu bar widget for managing multiple Claude OAuth accounts"
  homepage "https://github.com/japananh/aimonitor"

  # Universal binary works on both Intel and Apple Silicon.
  depends_on macos: ">= :sonoma"

  binary "aimonitor"
  app "AIMonitor.app"

  caveats <<~EOS
    aimonitor is unsigned in this beta. macOS Gatekeeper will refuse the
    first launch. Clear the quarantine attribute once with:

      xattr -dr com.apple.quarantine /Applications/AIMonitor.app

    Then start the menu bar widget from /Applications, or run

      aimonitor daemon run

    to start the headless watcher (useful for SSH / headless setups).
    Enable autostart at login with:

      aimonitor config set autostart true

    Uninstall removes the LaunchAgent + binary. To also drop the
    SQLite DB and aimonitor keyring entries, run BEFORE `brew uninstall`:

      aimonitor uninstall --purge
  EOS

  # Order matters: brew runs `uninstall` first, then deletes files,
  # then runs `zap` only if --zap was passed. quit + login_item make
  # sure the menu bar app stops AND its SMAppService login-item
  # registration is cleared — otherwise macOS keeps a dangling
  # Login Item pointing at a non-existent /Applications/AIMonitor.app.
  uninstall launchctl:  "dev.aimonitor.daemon",
            quit:       "dev.aimonitor.AIMonitor",
            login_item: "dev.aimonitor.AIMonitor"

  zap trash: [
    "~/Library/Application Support/aimonitor",
    "~/Library/Logs/aimonitor",
    "~/Library/Caches/aimonitor",
    "~/Library/Preferences/dev.aimonitor.AIMonitor.plist",
    "~/Library/LaunchAgents/dev.aimonitor.daemon.plist",
    "~/.config/aimonitor",
  ]
end
